# Generated by Django 5.0.3 on 2024-04-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_longlivedtoken_delete_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longlivedtoken',
            name='token',
            field=models.CharField(max_length=500),
        ),
    ]
