# Generated by Django 5.0.3 on 2024-05-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_optimizationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationresult',
            name='homeAttached',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='optimizationresult',
            name='name',
            field=models.CharField(default='default_value', max_length=500),
        ),
    ]
