# Generated by Django 5.0.3 on 2024-05-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_optimizationresult_homeattached_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationresult',
            name='homeToken',
            field=models.CharField(default='default_value', max_length=500),
        ),
    ]
